<?
require("./php.php");
head("Hučka 2005",True,0,"historie");?>
Již tradiční sedmý ročník akce pod názvem Hučka pořádal 43. oddíl Junáka Letící hvězda dne 3. prosince na DDM Hrádek. Přišli sem skupiny či jednotlivci jak z Třebíče, tak i skautky a skauti z Jemnice, z Moravských Budějovic a z Valče. Hrálo se divadlo, tančilo se a po letech se dokonce uskutečnila i ruská ruleta (ne však ta s tou pistolí, ale divadlo, kde byly na přípravu vyhrazeny pouze dvě minuty). Občerstvení zařídili členové 43. oddílu a jejich maminky domácími buchtami, perníky a cukrovím a k pití zde byly limonády ZON. Po vstupu do budovy měli návštěvníci možnost shlédnout fotky z akcí „čtyřicet trojky“ a její internetové stránky (www.leticihvezda.wz.cz).<br>
Poté vstoupili do sálu, kde se vše odehrávalo. Usmívala se na ně třímetrová žirafa a také další žirafy, ne už tak vysoké. Z trávy vykukoval slon a rostly baobaby a byl zde i panoramatický pohled na hory a slunce nad nimi… Toto všechno bylo bohužel pouze namalováno barvami na papíře. Krátce po plánovaném začátku, to bylo ve 4 hodiny, vše začalo.<br>
V sále se poschovávali domorodci (jako vždy zahajoval 43. oddíl zahajovací scénkou). Na pódium letí klobouk. Začíná hrát africká hudba. A přichází náčelník. Náčelník křičí, černoši odpovídají a začínají se slézat na pódium. Domorodci tancují okolo klobouku. A přichází šaman. Jednou bouchne holí o zem. Domorodci ustrnuli ve svých pozicích. Druhé bouchnutí a domorodci si sedají na zem. Šaman mluví a mluví a mluví, ukazuje na klobouk a domorodci na něj jen vykuleně hledí. Šaman skončil, převrátil klobouk a domorodci z něj něco vytahují. Jsou to písmena, oni ovšem neví co to je. Písmo neznají. Je to pět písmen. Drží je pět domorodců a ukazují je ostatním, kteří tancují okolo nich. Písmena si vyměňují. A hudba končí a je tma. Znovu se rozsvěcí a vidíme nápis HUČKA držený pěti domorodci, které drží deset dalších. Je konec domorodci seskakují dolů a je potlesk.<br>
Zahájení skončilo a nastupuje první scénka, po ní druhá, po ní třetí… a nakonec poslední šestá. A přichází hlasování. Po tomto přichází druhá kategorie a tou je tanec. Dalších pět představení a druhé hlasování, vyhlášení nejlepšího herce, tím je světluška Išta za roli v divadelní scéně Modroočko. Rozdávaly se nejen diplomy, ale také perníky velikosti podle umístění.<br>
Hučka se oficiálně ukončila a následovala ruská ruleta, na tu zde zůstali jen ti nejodvážnější. Sehrálo se 5 scének Lachtan loví veverku, Vypadáš skvěle, Harry Potter, Maturita a Obchod se zlatem a další scénka 43. oddílu. Protože ji nestihl nacvičit, kvůli organizaci dalších akcí a tak byla sehrána s minimálním počtem rekvizit a herců. Její téma byly sestříhané písně od Jaromíra Nohavici, zazněl Milionář, Fotbal, Zatím co se koupeš, Básnířka a další.<br>
Po ruské ruletě zůstali 43. oddíl a skauti a skautky z Jemnice a z Moravských Budějovic. Promítaly se fotky a videa z různých akcí a táborů, prostě hezký večer v hezké společnosti. Skautky z Jemnice zůstaly i na přespání. Ráno se uklízelo a uklízelo a uklízelo. A v jedenáct hodin končí Hučka i pro členy 43. oddílu.<br>


<? foot(True);?>