<?
require("./php.php");
head("Hučka 1999",True,0,"historie");
?>
  Podle mého mínění byla tato akce nejlepší festival určený pro celou veřejnost, který pořádal náš oddíl. Teda aspoň po tu krátkou dobu, co jsem v oddíle. ironicky Že teda takových akcí bylo, co? Vše se řádně připravovalo předem a dlouhodobé koncentrování energie se vyplatilo. Základem celé akce bylo vystupování široké veřejnosti na jevišti. U písní začínaje, přes divadelní scény, ruskou ruletou konče. Účastníci vyplnili uchazečskou přihlášku, zaplatili dobrovolné vstupné, dostali upomínkový kamínek a mohli vystupovat. Veškeří umělci i neumělci byli výborní. Hlavně naše družina. Svědci naší scénky určitě snahu ocení, i když svědků nebylo mnoho.<br>
    Další velkou zajímavostí a důvodem, aby se vystupující snažili byly pestré ceny. Hlavně naše oddílové tričko. Co se týče hodnocení vystupujících, tak vše bylo rozděleno do několika kategorií a v každé kategorii někdo vyhrál. Hlasy byly uddělovány přítomnými diváky, kterých nebylo vůbec málo, musím přiznat, že tak hojný počet lidí jsem nečekal. Nakonec se všechny hlasy sečetly a kdo jich měl nejvíc, ten vyhrál hlavní cenu. Vítězi se stali Bizoni a jeden velice malý, ale přímoúměrně k výšce tak nadaný recitátor se svými básničkami, které pobavily celý sál. Teď jsem si tak vzpoměl.<br> 
    Celá akce se odehrávala na domku Švabinského, proto touto cestou musím poděkovat Honzovi, který nám domek zapůjčil. Malým antikladem pro malé děti byla pozdější doba konce. Vždyť malí špunti (nic proti Lachtane) jsou zvyklí jít po večerníčku spát. Na konci, kdy se všechno dalo do původního stavu, jsme se sešli, my pořadatelé (všichni z oddílu) a samozřejmě člověk je tvor zvědavý, tak nám nedalo a podívali jsme se na výdělek z celé akce. Ten činil asi 500Kč. Zachovali jsme se jako správní skauti a výdělek jsme věnovali „bratrům“ v Chorvatsku.<br>
    Na to, že nepatříme mezi oddíly, které pořádají takové akce každý měsíc, musím uznat Hučku, jako akci velice zdařilou. Zvláštní dík patří rodičům, kteří přispěli výborným občerstvením a chci taky poděkovat lidem, kteří přispěli výborným občerstvením a chci taky poděkovat lidem, kteří mě odpustí za zvorání naší scénky. Už se předem těším na příští akci podobného druhu.<br><br>                                                                                                                                Zelí  


<? foot(True);?>