<?
require("./php.php");
head("Hučka 2007",True,0);
?>
V posledních letech nám přestávala vyhovovat kapacita stávajících prostor. Z tohoto důvodu jsme se rozhodli v letošním roce udělat Hučku v novém kabátě, nabídnout účastníkům doplňkové aktivity a díky spolupráci s Městským kulturním střediskem KVIZ Třebíč v Klubu Hájek jsme našli i vyhovující prostory. Hučka také začala již o den dříve večerním filmovým festivalem amatérsky natočených filmů. Z Hučky se tak stává opravdový festival. V rámci filmového večera byla uvedena asi dvacítka krátkometrážních snímků různých žánrů. Vítězný film “Pan Panožka”, jehož autorem je Turistický oddíl mládeže Čtverka Znojmo, byl zvolen hlasováním diváků.<br>
Dopolední program se odehrál v Klubu Hájek, kde jsme uspořádali dopolední sekci dílen a seminářů o herectví, fotografování, filmování a divadelním tanci. Dopolední programy skončili ve dvě hodiny, ale už kolem třetí začali do sálu přicházet herci i první diváci. Celý shon a příprava sálu vyvrcholila ve čtyři hodiny odpoledne, když 43. oddíl Letící hvězda zahájil divadelní představení Maorským tancem. Jakmile zaskakující moderátorská dvojice uvedla první divadlo, roztočil se kolotoč divadelních scének. Na jevišti se postupně vystřídali skautky a světlušky z Moravských Budějovic, TOM Čtverka ze Znojma, Amazonky z Třebíče, TO Dakota, 4. oddíl Vodních Skautů Žlutá ponorka a 7. ROJ SASANKY. Skončila poslední scénka a mohli jsme se pustit do diváckého hlasování o nejlepší divadlo a nejlepšího herce. Během přestávky se po darovaných perníčcích, loupáčcích, napečených buchtách a zonkách jen zaprášilo.  Než bylo hlasování vyhodnoceno, představila  se zatím na scéně dvě taneční vystoupení Hříšného tance a Slepic. Pak přišlo na řadu všemi očekávané vyhodnocení. Na prvním místě se umístil TOM Čtverka ze Znojma se svým divadlem Uvědomělá přísloví. Na druhém Amazonky Třebíč a třetí místo získaly Světlušky z Moravských Budějovic.<br>
Cenu za nejlepšího herce si odnesl Krokodýl ze scénky Jak Amazonky ke své náčelnici přišly. Závěr patřil bíle oděným hochům z kapely Lunetic. Konečně také dorazila dlouho očekávaná profesionální moderátorka, která se stačila již jen rozloučit a Hučka pro tento rok skončila.<br>


<? foot(True);?>